# Response types
TYPE_SUCCESS = "success"
TYPE_ERROR = "error"

# Actions
ACTION_CONNECT = "connect"
ACTION_SUBSCRIBE = "subscribe"
ACTION_UNSUBSCRIBE = "unsubscribe"
ACTION_DISCONNECT = "disconnect"
ACTION_UPDATE = "update"
ACTION_INITIAL_RESULT = "initial_result"

# Error codes
ERR_UNKNOWN_ACTION = "UNKNOWN_ACTION"
ERR_ALREADY_SUBSCRIBED = "ALREADY_SUBSCRIBED"
ERR_NOT_SUBSCRIBED = "NOT_SUBSCRIBED"
ERR_POLL_NOT_FOUND = "POLL_NOT_FOUND"
ERR_INTERNAL = "INTERNAL_ERROR"
ERR_POLL_DELETED = "POLL_DELETED"
